### ISSUE TITLE
PNGs over a certain size do not load in the browser

### ISSUE THREAD

**Issue by linknm** [configwizard/greenfinch.react#2]
When you try to view on the browser a PNG uploaded that goes over a certain file size, you get a server error instead of seeing the file.

Steps:

1. Create or open a new public container.
2. Select "Upload to this Container" and select a PNG of at least 91 KB in size.
3. Click on "Click to view file in web browser".

You will then end up with a browser tab showing a server error 502 instead of seeing the image file. I don't the minimum file size that triggers this. A very small PNG file such as a 2KB one does not trigger it. This could also be a server-side issue, though, as you can still download the PNG file from NeoFS without issues through Greenfinch

[Example of a public PNG file that is around 91KB in file size.](https://http.testnet.fs.neo.org/6PKtHWHgzK8XfXSEPjF4d1QSjpphzebWwwp2B7C91kX7/DVKExorVN2hAz71zkREzjVDQStBFbjboFf5cRfHV3qjM)

**Comment by linknm** [comment]
Tried to load the file once more and actually got a different response from the server this time.

`could not receive object: read header: read response: rpc error: code = Unavailable desc = error reading from server: EOF`

**Comment by linknm** [comment]
Issue seems to be fixed now.

**Comment by amlwwalker** [comment]
Great news, this was an issue with the HTTP node and not greenfinch as it turned out, but all good - it was a necessary for greenfinch
